### ISSUE TITLE
OpenTTD 14 removed share owners

### ISSUE THREAD

**Issue by rubidium42** [ropenttd/gopenttd#3]
With OpenTTD/OpenTTD#10709 company shares have been removed, including from he admin packet with an increment of the protocol version number.

I'm not sure what is going to happen, since I have not set up `go` and as such can't run the code. However, I suspect it's either bailing out because the packet does not have enough information for the decoding to complete, or it's returning the company with id 0 as owner of all the shares. The latter might trip up users of this library, as it might think that company 0 owns a lot of other companies.

https://github.com/ropenttd/gopenttd/blob/ccf1a513cc9cf1ab85796017777d6fd1aab7317a/pkg/admin/packets/packets_server.go#L275-L278

**Comment by duckfullstop** [comment]
Thanks for letting me know, and sorry for the delay! I've pushed a rudimentary fix to [the ottd14 branch](https://github.com/ropenttd/gopenttd/tree/ottd14) - any chance someone can just check for compatibility?
